version: 2

sources:
  - name: in_class
    tables:
      - name: customers
        columns:
          - name: id
            data_type: int64
          - name: first_name
            data_type: string
          - name: last_name
            data_type: string

      - name: my_first_dbt_model
        columns:
          - name: id
            data_type: int64

      - name: my_second_dbt_model
        columns:
          - name: id
            data_type: int64

      - name: my_third_dbt_model
        columns:
          - name: id
            data_type: int64